version: "3.7"
services:

  database:
    image: jasmit/pgpods-service:v0.2.0 
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    secrets:
      - db-password
    volumes:
      - db-data:/opt/app/postgres/data
    networks:
      - backend-network
    ports:
      - 5432:5432

secrets:
  db-password:
    file: ./.secrets-db-password 

networks:
  backend-network:

volumes:
  db-data:
    external: true
