version: "3.7"
services:

  database:
    build: pgpods 
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    secrets:
      - db-password
    volumes:
      - postgres-data:/opt/app/postgres/data
    networks:
      - backend-network
    ports:
      - 5432:5432

secrets:
  db-password:
    file: ./.secrets-db-password 

networks:
  backend-network:

volumes:
  postgres-data:
    external: true
