#!/usr/bin/env bash
set -x
#

kubectl delete pvc pgpods-base-claim
kubectl delete pvc pgpods-base-claim --namespace com-jasmit-pgpods
kubectl delete pvc pgpods-data-claim --namespace com-jasmit-pgpods
kubectl delete pvc pgpods-xlog-claim --namespace com-jasmit-pgpods
kubectl delete pvc pgpods-bkup-claim --namespace com-jasmit-pgpods

kubectl delete pv pgpods-base-volume
kubectl delete pv pgpods-base-volume
kubectl delete pv pgpods-data-volume
kubectl delete pv pgpods-xlog-volume
kubectl delete pv pgpods-bkup-volume

sudo su -c "rm -rf /opt/app/storage/pgpods"
# sudo su -c "rm -rf /opt/app/storage/pt0210gi/*"
# sudo su -c "rm -rf /opt/app/storage/pt0310gi/*"
# sudo su -c "rm -rf /opt/app/storage/pt0410gi/*"

# sudo su -c "rm /opt/app/storage/pt0110gi/.*"
# sudo su -c "rm /opt/app/storage/pt0210gi/.*"

kubectl get pv,pvc

ls -ltR /opt/app/pgpods

exit 0

