
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgpods-volume-claim 
spec:
  storageClassName: pgpods-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi

---
